import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.*;

/**
 * The {@code RevivePetPanel} class provides a graphical user interface panel
 * that allows users to revive pets from different save files.
 * <p>
 * The panel displays a title, pet status, a dropdown to select a save slot,
 * and Yes/No buttons to confirm or cancel the pet revival action.
 * When a pet is revived, its data is saved to a CSV file and updated in the PetManager.
 * </p>
 */

 /**
  * This portion of the GUI class is generated by chatgpt
  */
public class RevivePetPanel extends JPanel {
    private Pet pet; 
    private JLabel statusLabel; 
    private JButton yesButton; 
    private JButton noButton; 
    private JComboBox<String> saveSlotDropdown; 

    /**
     * Constructs a new {@code RevivePetPanel} and initializes its components.
     * <p>
     * The panel uses a BorderLayout with a title label at the top, a status label in the center,
     * and a bottom panel that contains the save slot dropdown and buttons arranged vertically.
     * The initial pet status is loaded based on the default save slot.
     * </p>
     */
    public RevivePetPanel() {
        setLayout(new BorderLayout());   // Set the layout and background color of the panel
        setBackground(Color.WHITE);

        JLabel titleLabel = new JLabel("Revive Pet", SwingConstants.CENTER);  // Create and configure the title label
        titleLabel.setFont(new Font("Arial", Font.BOLD, 36));
        titleLabel.setBorder(BorderFactory.createEmptyBorder(20, 0, 20, 0));
        add(titleLabel, BorderLayout.NORTH);

        statusLabel = new JLabel("Select a save slot to view pet status.", SwingConstants.CENTER); // Create and configure the status label
        statusLabel.setFont(new Font("Arial", Font.PLAIN, 24));
        add(statusLabel, BorderLayout.CENTER);

        JPanel bottomPanel = new JPanel(); // Create the bottom panel that contains the save slot dropdown and buttons
        bottomPanel.setLayout(new BoxLayout(bottomPanel, BoxLayout.Y_AXIS));
        bottomPanel.setOpaque(false);
        bottomPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));

     
        String[] saveOptions = {"save1", "save2", "save3"};  // Initialize the dropdown with save slot options
        saveSlotDropdown = new JComboBox<>(saveOptions);
        saveSlotDropdown.setMaximumSize(new Dimension(150, 30));
        saveSlotDropdown.setAlignmentX(Component.CENTER_ALIGNMENT);
        saveSlotDropdown.addActionListener(e-> updatePetStatus());   // Update pet status when a different save slot is selected

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10)); // Create a panel for the Yes and No buttons.
        buttonPanel.setOpaque(false);

        yesButton = new JButton("Yes"); // Create a panel for the Yes button
        yesButton.setFont(new Font("Arial", Font.BOLD, 22));
        yesButton.setPreferredSize(new Dimension(120, 60));
        yesButton.addActionListener((ActionEvent e) -> reviveSelectedPet());

        noButton = new JButton("No"); // Create a panel for the No button
        noButton.setFont(new Font("Arial", Font.BOLD, 22));
        noButton.setPreferredSize(new Dimension(120, 60));
        noButton.addActionListener((ActionEvent e) ->
                JOptionPane.showMessageDialog(this, "Pet remains unchanged.", "Info", JOptionPane.INFORMATION_MESSAGE)
        );

        buttonPanel.add(yesButton);
        buttonPanel.add(noButton);

        bottomPanel.add(saveSlotDropdown);
        bottomPanel.add(Box.createVerticalStrut(10));
        bottomPanel.add(buttonPanel);

        add(bottomPanel, BorderLayout.SOUTH);

        
        updatePetStatus(); // Load the pet status for the initially selected save slot
    }

    /**
     * This concludes the portion generated by chatgpt 
     */

    /**
     * Updates the displayed pet status based on the currently selected save slot.
     * <p>
     * Retrieves the {@link Pet} instance associated with the selected save slot from the {@link PetManager}
     * and updates the status label with the pet's current state.
     * </p>
     * @author Jessamine Li
     * @author Jonathan Lin
     */
    private void updatePetStatus() {
        String slot = (String) saveSlotDropdown.getSelectedItem(); // Retrieve the selected save slot from the dropdown and cast it to a String
        pet = PetManager.getPet(slot);  // Get the Pet associated with the selected save slot from PetManager
        statusLabel.setText(getStatusText()); // Update the status label with the current pet's status text
    }

     /**
     * Revives the pet selected in the save slot if it is dead.
     * <p>
     * If the pet is dead, it is revived using the {@code Command.revive} method, saved to the corresponding file,
     * updated in the {@link PetManager}, and a success message is displayed.
     * If the pet is already alive, an informational message is shown.
     * </p>
     */
    private void reviveSelectedPet() {
        String slot = (String) saveSlotDropdown.getSelectedItem(); // Retrieve the selected save slot from the dropdown
        System.out.println("Selected slot: " + slot); // Debug: Log the selected slot
        System.out.println("Pet state before revival: " + pet.getState()); // Debug: Log the pet's state before revival

        if (pet.isDead()) { // Check if the current pet is dead
            pet = Command.revive(pet); // Revive the pet using the Command.revive method and assign the revived pet back to the pet variable
            System.out.println("Pet state after revival: " + pet.getState()); // Debug: Log the pet's state after revival

            savePetToFile(pet, slot); // Save the revived pet's data to the appropriate file based on the selected save slot
            PetManager.setPet(slot, pet);
            JOptionPane.showMessageDialog(this, "Pet revived! Stats set to maximum.", "Success", JOptionPane.INFORMATION_MESSAGE);
            updatePetStatus();  // Refresh the pet status display after revival
        } else {
            JOptionPane.showMessageDialog(this, "Pet is already alive.", "Info", JOptionPane.INFORMATION_MESSAGE); // If the pet is already alive, state pet is already alive
        }
    }

    /**
     * Generates a status text message for the pet.
     * <p>
     * If the pet is dead, a message prompting the user to revive the pet is returned.
     * Otherwise, an HTML formatted string displaying the pet's statistics is returned.
     * </p>
     *
     * @return a {@code String} representing the pet's status.
     */
    private String getStatusText() {
        if (pet.isDead()) { // Check if pet is dead
            return "Pet is dead. Click Yes to revive."; // Return message if pet is dead
        } else { // Return an HTML formated string displaying pet statistics if pet is alive
            return String.format("<html>Pet is alive!<br>Health: %d<br>Fullness: %d<br>Sleep: %d<br>Happiness: %d<br>Love: %d</html>",
                    pet.getHealth(),  // Return all vital stats
                    pet.getFullness(), 
                    pet.getSleep(), 
                    pet.getHappiness(), 
                    pet.getLove()); 
        }
    }

      /**
     * Saves the specified pet's data to a CSV file corresponding to the given save slot.
     * <p>
     * The CSV file is stored at the path: "src/model/saveFiles/{slot}/{slot}_pet.csv".
     * The saved file includes a header line and a line with the pet's attributes.
     * The pet's score is set to 0 and time played is set to "00:00" by default.
     * </p>
     *
     * @param pet  the {@link Pet} instance to be saved.
     * @param slot the save slot identifier associated with the pet.
     */
    private void savePetToFile(Pet pet, String slot) {
        String path = "src/model/saveFiles/" + slot + "/" + slot + "_pet.csv"; // Construct the file path based on the selected save slot
        try (PrintWriter writer = new PrintWriter(new FileWriter(path))) {
            writer.println("name,type,state,fullness,energy,health,love,happiness,score,time played"); // Write the CSV header line to the file.
            writer.printf("%s,%s,%s,%d,%d,%d,%d,%d,%d,%s%n",
                    pet.getName(), 
                    pet.getTypeString(), 
                    pet.getState(),
                    pet.getFullness(), 
                    pet.getSleep(), 
                    pet.getHealth(),
                    pet.getLove(), 
                    pet.getHappiness(),
                    0,
                    "00:00");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}